vim.g.mapleader = " "

require("yura.lazy")
require("yura.core.options")
require("yura.core.keymaps")
require("yura.plugins.comment")
require("yura.plugins.nvim-tree")
require("yura.plugins.lualine")
require("yura.plugins.telescope")
require("yura.plugins.nvim-cmp")
require("yura.plugins.lsp.mason")
require("yura.plugins.lsp.lspsaga")
require("yura.plugins.lsp.lspconfig")
require("yura.plugins.lsp.null-ls")
require("yura.plugins.autopairs")
require("yura.plugins.treesitter")
require("yura.plugins.gitsigns")
require("yura.plugins.harpoon")
require("yura.plugins.lsp")
